version: '3'

services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: sekthor
      MYSQL_PASSWORD: password
    port:
      - 3306:3306
    volumes:
      - mysql_db: /var/lib/mysql
volumes:
  mysql_db:
